import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ArrowUpRight } from "lucide-react";
import { getProject, projects } from "@/content/projects";

export function generateStaticParams(){return projects.map(p=>({slug:p.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=getProject(slug);return p?{title:p.title,description:p.summary}:{};}
export default async function ProjectPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const project=getProject(slug);if(!project)notFound();const index=projects.findIndex(p=>p.slug===project.slug);const next=projects[(index+1)%projects.length];return <main id="main" className="inner-page case-study"><div className="shell"><Link href="/#work" className="back-link"><ArrowLeft size={15}/> Back to work</Link><div className="case-hero"><div className="page-kicker"><span>CASE STUDY / {String(index+1).padStart(2,"0")}</span><span>{project.categories.join(" / ")}</span></div><h1>{project.title}</h1><p>{project.summary}</p><div className="case-stack">{project.stack.map(s=><span key={s}>{s}</span>)}</div></div><div className="case-cover"><Image src={project.visual} alt={`${project.title} visual`} fill priority sizes="100vw"/></div><div className="case-body"><aside><span>OVERVIEW</span><p>Representative case-study structure. Replace placeholder content with public project facts before publishing.</p></aside><div className="case-copy"><section><span>01 / CONTEXT</span><h2>What was being built?</h2><p>{project.description}</p></section><section><span>02 / PROBLEM</span><h2>Where the system gets difficult.</h2><p>{project.challenge}</p></section><section><span>03 / APPROACH</span><h2>Make behaviour explicit.</h2><p>{project.solution}</p></section><section><span>04 / DECISIONS</span><h2>Key engineering decisions.</h2><ol>{project.decisions.map((d,i)=><li key={d}><span>0{i+1}</span>{d}</li>)}</ol></section><section><span>05 / RELIABILITY</span><h2>Failure paths considered.</h2><div className="reliability-grid">{project.reliability.map(r=><div key={r}>{r}</div>)}</div></section></div></div><Link href={`/work/${next.slug}`} className="next-project"><span>NEXT PROJECT</span><strong>{next.title}</strong><ArrowUpRight/></Link></div></main>}
