const header=document.querySelector('.site-header');const menuBtn=document.querySelector('.menu-button');const menu=document.querySelector('.mobile-menu');
addEventListener('scroll',()=>header.classList.toggle('is-scrolled',scrollY>40),{passive:true});
menuBtn?.addEventListener('click',()=>{const open=menu.classList.toggle('open');menuBtn.setAttribute('aria-expanded',String(open));menuBtn.textContent=open?'×':'☰';document.body.classList.toggle('menu-open',open);menu.querySelectorAll('a').forEach(a=>a.tabIndex=open?0:-1)});
document.querySelectorAll('.mobile-menu a').forEach(a=>a.addEventListener('click',()=>{menu.classList.remove('open');document.body.classList.remove('menu-open');menuBtn.setAttribute('aria-expanded','false');menuBtn.textContent='☰';menu.querySelectorAll('a').forEach(x=>x.tabIndex=-1)}));
document.querySelectorAll('.stack-plane').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.stack-plane').forEach(x=>x.classList.remove('active'));b.classList.add('active')}));
const scenarios={
'BUILD A PRODUCT':['> project:init','analysing requirements...','architecture selected','tasks decomposed','implementation running','','✓ validation','✓ error paths','✓ async flow','✓ deployment config','','status: ready to ship'],
'AUTOMATE A WORKFLOW':['> workflow:map','observing repeated actions...','inputs normalised','failure states mapped','queue policy applied','','✓ retries bounded','✓ stale state guarded','✓ status visible','','status: automation ready'],
'DEPLOY A SERVICE':['> deploy:prepare','checking revision...','environment loaded','health checks armed','release running','','✓ proxy config','✓ service healthy','✓ rollback path ready','','status: production / healthy']};
const out=document.querySelector('#console-output');function render(mode){out.innerHTML='';scenarios[mode].forEach(line=>{const s=document.createElement('span');s.textContent=line||' ';if(line.startsWith('✓'))s.className='ok';if(line.startsWith('status'))s.className='status';out.appendChild(s)});document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode))}render('BUILD A PRODUCT');document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>render(b.dataset.mode)));
const engine=document.querySelector('.preview-engine');const glow=document.querySelector('.pointer-glow');const status=document.querySelector('.scene-status span:last-child');
function cinematicScroll(){const max=Math.max(1,document.documentElement.scrollHeight-innerHeight);const p=Math.min(1,scrollY/max);document.documentElement.style.setProperty('--page-progress',p);if(engine){const heroP=Math.min(1,scrollY/(innerHeight*1.35));engine.style.transform=`translateY(calc(-48% - ${heroP*6}px)) rotateY(${heroP*9}deg) rotateX(${heroP*2}deg) scale(${1+heroP*.035})`;engine.style.filter=`brightness(${1+heroP*.08}) saturate(${1+heroP*.12})`}if(status){const phase=scrollY<innerHeight*.2?'DORMANT':scrollY<innerHeight*.65?'OPEN':scrollY<innerHeight*1.4?'INSPECT':'BUILD';status.textContent='STATE / '+phase}}
addEventListener('scroll',cinematicScroll,{passive:true});cinematicScroll();
addEventListener('pointermove',e=>{if(e.pointerType==='touch'||!glow)return;glow.style.transform=`translate3d(${e.clientX}px,${e.clientY}px,0) translate(-50%,-50%)`;if(engine&&scrollY<innerHeight*1.2){const x=(e.clientX/innerWidth-.5)*5,y=(e.clientY/innerHeight-.5)*-4;engine.style.setProperty('--mx',x+'deg');engine.style.setProperty('--my',y+'deg')}} ,{passive:true});